### ISSUE TITLE
change current code style to be valid with black, isort and flake8

### ISSUE THREAD

**Issue by FelixTheC** [PFython/cleverdict#40]
- [ ] create a `pyprojects.toml`
- [ ] add necessary settings for black, isort and flake8 (see below)
- [ ] run all linters to change the style initialy before merging https://github.com/PFython/cleverdict/pull/38

```toml
[tool.black]
line-length = 100
target-version = ['py39']

[tool.isort]
combine_as_imports = true
line_length = 100
profile = "black"
```
